LUAC = "C:/Program Files/Gideros/Tools/luac.exe"

all: .tmp/actions.lua.bin .tmp/board.lua.bin .tmp/gameManager.lua.bin .tmp/gridBox.lua.bin .tmp/init.lua.bin .tmp/main.lua.bin .tmp/major.lua.bin .tmp/mapsign.lua.bin .tmp/meeple.lua.bin .tmp/player.lua.bin .tmp/playerBoard.lua.bin .tmp/rscConverter.lua.bin .tmp/toolbox.lua.bin .tmp/ui.lua.bin

.tmp/actions.lua.bin: assets/actions.lua
	$(LUAC) -o ".tmp/actions.lua.bin" "assets/actions.lua"

.tmp/board.lua.bin: assets/board.lua
	$(LUAC) -o ".tmp/board.lua.bin" "assets/board.lua"

.tmp/gameManager.lua.bin: assets/gameManager.lua
	$(LUAC) -o ".tmp/gameManager.lua.bin" "assets/gameManager.lua"

.tmp/gridBox.lua.bin: assets/gridBox.lua
	$(LUAC) -o ".tmp/gridBox.lua.bin" "assets/gridBox.lua"

.tmp/init.lua.bin: assets/init.lua
	$(LUAC) -o ".tmp/init.lua.bin" "assets/init.lua"

.tmp/main.lua.bin: assets/main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "assets/main.lua"

.tmp/major.lua.bin: assets/major.lua
	$(LUAC) -o ".tmp/major.lua.bin" "assets/major.lua"

.tmp/mapsign.lua.bin: assets/mapsign.lua
	$(LUAC) -o ".tmp/mapsign.lua.bin" "assets/mapsign.lua"

.tmp/meeple.lua.bin: assets/meeple.lua
	$(LUAC) -o ".tmp/meeple.lua.bin" "assets/meeple.lua"

.tmp/player.lua.bin: assets/player.lua
	$(LUAC) -o ".tmp/player.lua.bin" "assets/player.lua"

.tmp/playerBoard.lua.bin: assets/playerBoard.lua
	$(LUAC) -o ".tmp/playerBoard.lua.bin" "assets/playerBoard.lua"

.tmp/rscConverter.lua.bin: assets/rscConverter.lua
	$(LUAC) -o ".tmp/rscConverter.lua.bin" "assets/rscConverter.lua"

.tmp/toolbox.lua.bin: assets/toolbox.lua
	$(LUAC) -o ".tmp/toolbox.lua.bin" "assets/toolbox.lua"

.tmp/ui.lua.bin: assets/ui.lua
	$(LUAC) -o ".tmp/ui.lua.bin" "assets/ui.lua"

